virt-s1/bootc-workflow-test

anaconda.sh
The rhel repo used by rhel bootc image is too old, let's use latest for a workaround
=> test: use latest for rhel repo instead of rhel bootc image repo

.github/workflows/upload_rhel9_ami.yml
ARCH for both x86_64 and aarch64
=> ci: use more environments in upload rhel9 ami workflow

anaconda.sh, bib-image.sh, os-replace.sh
transient root and composefs are only landed on centos-bootc-dev and fedora-eln images
=> test: update bib-image.sh to support transient root

.github/workflows/anaconda.yml
Libvirt and qemu-kvm on CS9 can't work well with httpboot. Let's change CS9 anadonda test runner to Fedora 39
=> ci: run cs9 anaconda test on Fedora 39 runner

playbooks/check-system.yaml
Due to bug https://github.com/CentOS/centos-bootc/issues/354
=> test: skip persistent log case on RHEL test

.github/workflows/os-replace.yml, tmt/plans/os-replace.fmf
Corss building needs `qemu-user-static`. It should be installed in `prepare`.
=> test: install qemu-user-static as cross build dependency

playbooks/install.yaml
Bind mounting `/var/lib/containers` should work with the latest bootc and is the recommendation.
=> playbooks/install: Drop skopeo dependency

.github/workflows/upload_rhel9_ami.yml, renovate.json, tools/Dockerfile
Renovate will bump fedora image to the latest supported release for the Dockerfile and the github action workflow. See example: https://github.com/platform-engineering-org-test/renovate_test_2/pull/17
=> Renovating fedora to the latest supported release

.github/workflows/update_cs9_ami.yml, .github/workflows/upload_rhel9_ami.yml
This PR removed ami image cron update but use manual update instead.
=> ci: do not run ami image update cronly but manually update instead

.github/workflows/bib-image.yml
Cross build needs virtualization support, bib-image tmt plan is updated to use virtualization runner for cross build test
build aarch64 on x86_64 server test log: http://artifacts.osci.redhat.com/testing-farm/7274bfa1-0bde-4eb7-becf-ce2d340abe0e
=> ci: update bib-image workflow to support cross build test

.github/workflows/anaconda.yml, .github/workflows/bib-image.yml, .github/workflows/os-replace.yml
Avoid TF CS9 runner deployment issue
=> ci: run all CS9 test on Fedora 40

.github/workflows/os-replace.yml, os-replace.sh, playbooks/check-system.yaml, playbooks/deploy-beaker.yaml, playbooks/install.yaml, playbooks/remove.yaml, playbooks/rollback.yaml, playbooks/templates/beaker-job.j2, playbooks/upgrade.yaml, tmt/plans/os-replace.fmf, tmt/tests/os-replace.fmf, tmt/tests/test.sh
This PR adds os replace test on bare metal server from beaker. It covered bootc install for bare metal server scenario.
This PR only support standard partition. Will support LVM later.
- x86_64+BIOS+autopart+CS9: http://artifacts.osci.redhat.com/testing-farm/fcf46306-cdfb-48c0-a2c4-fe1c1c1640ad/
Let's run some regression tests.
=> test: add beaker bare metal os replace test

.github/workflows/os-replace.yml, .tekton/rhel-bootc-integration-tests.yaml, .tekton/testing-farm.yaml, bib-image.sh, os-replace.sh, playbooks/deploy-azure.yaml, playbooks/remove.yaml, tmt/plans/bib-image.fmf, tmt/plans/os-replace.fmf, tools/upload_vhd.sh
fix https://github.com/virt-s1/bootc-workflow-test/issues/195
=> test: add azure test for os-replace

playbooks/deploy-libvirt.yaml
Since compose CentOS-Stream-9-20240328.0, CentOS Stream 9 qcow2 image can't boot. Let's use old one as a workaround
=> test: workaround issue RHEL-30952

.github/workflows/anaconda.yml, .github/workflows/bib-image.yml, .github/workflows/os-replace.yml
It's due to issue https://github.com/sclorg/testing-farm-as-github-action/pull/137#issuecomment-2039397156
=> ci: rollback testing farm action to v1

playbooks/deploy-beaker.yaml, playbooks/deploy-libvirt.yaml, playbooks/remove.yaml, tmt/plans/anaconda.fmf
We have two issues recently:
1. CS9 builds two qcow2 images since `20240405.1`. That caused regrex failure. e.g. http://artifacts.osci.redhat.com/testing-farm/3a6eb0a5-ab17-4633-8e85-a563174dd903/
2. ansible galaxy server is not stable. Download collections filed a lot of times. e.g. http://artifacts.osci.redhat.com/testing-farm/9b4c02a8-301e-49de-b73c-5bdd3ca2d3d5/
This PR addresses those two issues.
=> test: fix cs9 image regex and glaxy server unstable issues

anaconda.sh
Not necessary anymore since https://github.com/ostreedev/ostree-rs-ext/commit/a5fadff0e8f8dca1ed06c82415feae27177f853f which is in 9.4
=> Drop --no-signature-verification

playbooks/deploy-azure.yaml, playbooks/templates/user-data.j2
According to https://github.com/MicrosoftDocs/azure-docs/blob/main/articles/virtual-machines/user-data.md#what-is-user-data, the new `--user-data` can save user data into Azure Instance Metadata Service(IMDS).
We can use `--user-data` for bootc install test on Azure.
=> test: use cloud-init to deploy azure instance

bib-image.sh, playbooks/check-system.yaml, playbooks/rollback.yaml, playbooks/upgrade.yaml
This PR uses `-v /var/lib/containers/storage:/var/lib/containers/storage` and `--local` to build RHEL image (private image repo). But it still needs to use `bootc switch` to do the first upgrade from container image registry, like quay.io. Otherwise system will upgrade from localhost.
@cgwalters This is the only solution to build cloud image from private image repo with bib.
cc @shi2wei3
=> test: build rhel bootc image with bib

anaconda.sh, bib-image.sh, os-replace.sh, tools/shared_lib.sh
Some container image repo is private, inspecting it needs auth first. This PR addresses this scenario.
=> test: add auth to inspect private container image registry

.github/workflows/anaconda.yml, .github/workflows/bib-image.yml, .github/workflows/os-replace.yml
This PR added rhel-9y snapshot image test trigger. That'll be easy to trigger snapshot or any scratch image test.
- `/test-rhel9y-snapshot` triggers `bootc install`, `anaconda install` and `bib` tests
- `/test-rhel9y-snapshot-anaconda` triggers `anaconda install` test
- `/test-rhel9y-snapshot-bib-image` triggers `bib` test
- `/test-rhel9y-snapshot-replace` triggers `bootc install` test
=> ci: add rhel-9y snapshot test triggers

.github/workflows/os-replace.yml, playbooks/deploy-beaker.yaml, playbooks/templates/beaker-job.j2
This PR will add LVM test in bootc install on beaker. bootc install will deploy on a beaker server deployed by autopart with `--type=lvm`.
=> test: add beaker autopart with lvm support

.github/workflows/bib-image.yml
This PR is a workaroud of issue #258
=> ci: run non corss build bib test on RHEL runner instead of F40

.github/workflows/bib-image.yml, bib-image.sh, tmt/plans/bib-image.fmf
This PR adds `bootc install to-disk` test. I know this test should be in `os-replace.sh`. But the test code will become duplicated and not easy to read if add into `os-replace.sh`. The best solution is to add the test into `bib-image.sh`. Simple code change.
I'll rename `bib-image.sh` to `image.sh` to test all kinds of images which can be built by `bib` or `bootc install to-disk`.
Testing Farm test result for this PR: http://artifacts.osci.redhat.com/testing-farm/a4d36b91-162a-4401-b2d1-cd418382a7f0
=> test: add bootc install to-disk test

playbooks/rollback.yaml
bootc rollback is only available on bootc-0.1.9 and above
=> test: use rpm-ostree rollback if bootc rollback is not available

.github/workflows/bib-image.yml, bib-image.sh, playbooks/deploy-libvirt.yaml, playbooks/remove.yaml, playbooks/templates/virt-install.bash.j2, tmt/plans/bib-image.fmf
This PR added bib `anaconda-iso` image building test.
- x86_64+bios result: http://artifacts.osci.redhat.com/testing-farm/049d2776-cca5-43d2-b295-89216ca02ef6/
- x86_64+uefi result: http://artifacts.osci.redhat.com/testing-farm/138a4c31-fbe7-4593-a3c1-da9eb516206d/
=> test: add bib anaconda-iso test

.github/workflows/bib-image.yml, bib-image.sh, tmt/plans/bib-image.fmf
This PR rebuilt anaconda iso for automatic installation test. The only automatic installation blocker is install mode command in kickstart. According to https://docs.centos.org/en-US/8-docs/advanced-install/assembly_kickstart-commands-and-options-reference/#text_kickstart-commands-for-installation-program-configuration-and-flow-control, for a fully automatic installation, you must either specify one of the available modes (graphical, text, or cmdline) in the Kickstart file.
In our case, the `text` will be added into kickstart file.
=> test: rebuild anaconda iso for automatic installation test

bib-image.sh
There's no downstream bib image for 9.5
=> test: only use downsteram bib image for 9.4

bib-image.sh, playbooks/rollback.yaml
This PR will test both public image (CentOS Stream and Fedora images) and private image (RHEL image) in bib image test.
Due to issue https://issues.redhat.com/browse/RHEL-34054, a workaround (`--local` and `localhost/image`) has to be used to build private image with bib.
=> test: add both public and private image test for bib

anaconda.sh
Compose in centos-bootc image does not exist any more, use latest-CentOS-Stream instead as a workaround
=> test: compose in centos-bootc image does not exist any more, use latest-CentOS-Stream instead

.github/workflows/anaconda.yml, .github/workflows/bib-image.yml, .github/workflows/os-replace.yml, anaconda.sh, bib-image.sh, files/copr-coreos-continuous.template, os-replace.sh, playbooks/check-system.yaml, playbooks/deploy-azure.yaml, playbooks/deploy-beaker.yaml, playbooks/deploy-gcp.yaml, playbooks/deploy-libvirt.yaml, playbooks/deploy-openstack.yaml, playbooks/install.yaml, tmt/plans/anaconda.fmf, tools/shared_lib.sh, tools/upload_gcp.yml, tools/upload_openstack.yml
This PR includes Fedora 40 and 41 (rawhide) image test.
=> test: add fedora bootc image test

.github/workflows/os-replace.yml, bib-image.sh, playbooks/check-system.yaml
This PR will change Fedora bib test runner to RHEL 9.5 runner for stability and openstack client install issue.
And this PR also add `--rootfs` in bib because fedora image does not include rootfs configuration in image.
=> Run bootc install test on RHEL 9.5 TF runner and add --rootfs in bib for fedora image

tmt/plans/anaconda.fmf, tmt/plans/bib-image.fmf, tmt/plans/os-replace.fmf
The new `fedora` tag is for fedora base image CI https://gitlab.com/fedora/bootc/base-image.
=> test: add fedora tag for fedora image CI

playbooks/check-system.yaml
workaround https://gitlab.com/fedora/bootc/base-images/-/issues/10
=> test: skip persistent log test on fedora 41
